// examples/react/FileManagerComponent.tsx
/**
 * FileManagerComponent — React 19 file manager UI
 *
 * Demonstrates the useFileAgent hook in a self-contained chat-style component.
 * Type a natural-language command and press Enter / click "Run" to execute it.
 *
 * Example commands
 * ──────────────────────────────────────────────────────────────────────
 *   Write a file at /notes.txt with content "Hello, OPFS!"
 *   Read /notes.txt
 *   List the files in /
 *   Create a directory at /projects
 *   Get file info for /notes.txt
 *   Copy /notes.txt to /notes-backup.txt
 *   Delete /notes-backup.txt
 * ──────────────────────────────────────────────────────────────────────
 *
 * Usage in a React 19 app
 * ───────────────────────
 *   import { FileManagerComponent } from './examples/react/FileManagerComponent'
 *
 *   export default function App() {
 *     return <FileManagerComponent />
 *   }
 */

import { useState, useRef, useEffect, type KeyboardEvent } from 'react'
import { useFileAgent } from './useFileAgent.ts'

// ─── sub-components ───────────────────────────────────────────────────────────

function StatusBadge({ status }: { status: string }) {
  const colours: Record<string, string> = {
    idle:          '#64748b',
    initialising:  '#f59e0b',
    ready:         '#22c55e',
    busy:          '#6366f1',
    error:         '#ef4444',
  }
  const colour = colours[status] ?? '#64748b'
  return (
    <span
      style={{
        display: 'inline-block',
        padding: '2px 10px',
        borderRadius: '999px',
        background: colour,
        color: '#fff',
        fontSize: '0.75rem',
        fontWeight: 600,
        textTransform: 'capitalize',
      }}
    >
      {status}
    </span>
  )
}

// ─── main component ───────────────────────────────────────────────────────────

export function FileManagerComponent() {
  const { status, lines, error, invoke, clearLines } = useFileAgent()
  const [prompt, setPrompt] = useState('')
  const outputRef = useRef<HTMLPreElement>(null)

  // Auto-scroll output as new lines arrive
  useEffect(() => {
    if (outputRef.current) {
      outputRef.current.scrollTop = outputRef.current.scrollHeight
    }
  }, [lines])

  async function handleRun() {
    const trimmed = prompt.trim()
    if (!trimmed || status !== 'ready') return
    setPrompt('')
    await invoke(trimmed)
  }

  function handleKeyDown(e: KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      void handleRun()
    }
  }

  return (
    <div
      style={{
        fontFamily: "'Segoe UI', system-ui, sans-serif",
        background: '#0f1117',
        color: '#e2e8f0',
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '2rem 1rem',
        gap: '1.5rem',
      }}
    >
      {/* Header */}
      <div style={{ textAlign: 'center' }}>
        <h1
          style={{
            fontSize: '1.75rem',
            fontWeight: 700,
            background: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            margin: 0,
          }}
        >
          OPFS File Agent
        </h1>
        <p style={{ color: '#94a3b8', marginTop: '0.4rem', fontSize: '0.9rem' }}>
          Powered by Strands Agents + opfs-worker (React&nbsp;19)
        </p>
      </div>

      {/* Status */}
      <StatusBadge status={status} />

      {/* Error banner */}
      {error && (
        <div
          style={{
            width: '100%',
            maxWidth: 760,
            background: '#450a0a',
            border: '1px solid #ef4444',
            borderRadius: '0.5rem',
            padding: '0.75rem 1rem',
            color: '#fca5a5',
            fontSize: '0.85rem',
          }}
        >
          {error}
        </div>
      )}

      {/* Output */}
      <div
        style={{
          width: '100%',
          maxWidth: 760,
          background: '#1e2130',
          border: '1px solid #2d3148',
          borderRadius: '0.75rem',
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            background: '#252840',
            padding: '0.6rem 1rem',
            fontSize: '0.78rem',
            color: '#6366f1',
            fontWeight: 600,
            letterSpacing: '0.05em',
            textTransform: 'uppercase',
            borderBottom: '1px solid #2d3148',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <span>Agent Output</span>
          <button
            onClick={clearLines}
            style={{
              background: 'none',
              border: '1px solid #4b5180',
              borderRadius: '0.25rem',
              color: '#94a3b8',
              cursor: 'pointer',
              fontSize: '0.72rem',
              padding: '2px 8px',
            }}
          >
            Clear
          </button>
        </div>
        <pre
          ref={outputRef}
          style={{
            margin: 0,
            padding: '1rem',
            whiteSpace: 'pre-wrap',
            fontFamily: "'Cascadia Code','Fira Code','Courier New',monospace",
            fontSize: '0.82rem',
            lineHeight: 1.7,
            color: '#a5f3fc',
            minHeight: 200,
            maxHeight: '50vh',
            overflowY: 'auto',
          }}
        >
          {lines.length
            ? lines.join('\n')
            : status === 'initialising'
              ? 'Initialising agent…'
              : 'Agent ready. Type a command below.'}
        </pre>
      </div>

      {/* Input */}
      <div style={{ width: '100%', maxWidth: 760, display: 'flex', gap: '0.5rem' }}>
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder='e.g. "Write a file at /hello.txt with content Hello!"'
          rows={2}
          disabled={status !== 'ready'}
          style={{
            flex: 1,
            background: '#1e2130',
            border: '1px solid #2d3148',
            borderRadius: '0.5rem',
            color: '#e2e8f0',
            fontSize: '0.9rem',
            padding: '0.6rem 0.9rem',
            resize: 'vertical',
            outline: 'none',
            fontFamily: 'inherit',
          }}
        />
        <button
          onClick={handleRun}
          disabled={status !== 'ready' || !prompt.trim()}
          style={{
            background: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
            border: 'none',
            borderRadius: '0.5rem',
            color: '#fff',
            cursor: status === 'ready' ? 'pointer' : 'not-allowed',
            fontWeight: 600,
            fontSize: '0.9rem',
            padding: '0 1.25rem',
            opacity: status === 'ready' && prompt.trim() ? 1 : 0.5,
            transition: 'opacity 0.2s',
          }}
        >
          Run
        </button>
      </div>

      <p style={{ color: '#475569', fontSize: '0.78rem', margin: 0 }}>
        Press <kbd style={{ background: '#1e2130', padding: '1px 5px', borderRadius: 3 }}>Enter</kbd> to run &nbsp;·&nbsp;
        <kbd style={{ background: '#1e2130', padding: '1px 5px', borderRadius: 3 }}>Shift+Enter</kbd> for newline
      </p>
    </div>
  )
}

// examples/angular/file-manager.component.ts
/**
 * FileManagerComponent — Angular 21 standalone component
 *
 * Chat-style UI for the OPFS-backed Strands Agent.
 * Uses Angular 21 signals, the new @if / @for control-flow syntax, and
 * injects FileAgentService for all agent interactions.
 *
 * Usage
 * ─────
 * 1. Add to your application routes or bootstrap it directly:
 *
 *    // main.ts
 *    import { bootstrapApplication } from '@angular/platform-browser'
 *    import { FileManagerComponent }  from './examples/angular/file-manager.component'
 *    bootstrapApplication(FileManagerComponent)
 *
 * 2. Or import into another standalone component:
 *
 *    @Component({
 *      imports: [FileManagerComponent],
 *      template: '<app-file-manager />'
 *    })
 *    export class AppComponent {}
 */

import {
  Component,
  OnInit,
  inject,
  signal,
  ElementRef,
  viewChild,
  afterEvery,
} from '@angular/core'
import { FormsModule } from '@angular/forms'
import { FileAgentService } from './file-manager.service.ts'

@Component({
  selector: 'app-file-manager',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './file-manager.component.html',
  styles: [`
    :host {
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
      background: #0f1117;
      color: #e2e8f0;
      font-family: 'Segoe UI', system-ui, sans-serif;
      padding: 2rem 1rem;
      gap: 1.5rem;
      box-sizing: border-box;
    }

    h1 {
      margin: 0;
      font-size: 1.75rem;
      font-weight: 700;
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }

    .subtitle {
      color: #94a3b8;
      font-size: 0.9rem;
      margin-top: 0.4rem;
    }

    .status-badge {
      display: inline-block;
      padding: 3px 12px;
      border-radius: 999px;
      color: #fff;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: capitalize;
    }

    .status-idle          { background: #64748b; }
    .status-initialising  { background: #f59e0b; }
    .status-ready         { background: #22c55e; }
    .status-busy          { background: #6366f1; }
    .status-error         { background: #ef4444; }

    .error-banner {
      width: 100%;
      max-width: 760px;
      background: #450a0a;
      border: 1px solid #ef4444;
      border-radius: 0.5rem;
      padding: 0.75rem 1rem;
      color: #fca5a5;
      font-size: 0.85rem;
    }

    .output-card {
      width: 100%;
      max-width: 760px;
      background: #1e2130;
      border: 1px solid #2d3148;
      border-radius: 0.75rem;
      overflow: hidden;
    }

    .output-header {
      background: #252840;
      padding: 0.6rem 1rem;
      font-size: 0.78rem;
      color: #6366f1;
      font-weight: 600;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      border-bottom: 1px solid #2d3148;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .clear-btn {
      background: none;
      border: 1px solid #4b5180;
      border-radius: 0.25rem;
      color: #94a3b8;
      cursor: pointer;
      font-size: 0.72rem;
      padding: 2px 8px;
    }

    pre.output {
      margin: 0;
      padding: 1rem;
      white-space: pre-wrap;
      font-family: 'Cascadia Code', 'Fira Code', 'Courier New', monospace;
      font-size: 0.82rem;
      line-height: 1.7;
      color: #a5f3fc;
      min-height: 200px;
      max-height: 50vh;
      overflow-y: auto;
    }

    .input-row {
      width: 100%;
      max-width: 760px;
      display: flex;
      gap: 0.5rem;
    }

    textarea {
      flex: 1;
      background: #1e2130;
      border: 1px solid #2d3148;
      border-radius: 0.5rem;
      color: #e2e8f0;
      font-family: inherit;
      font-size: 0.9rem;
      padding: 0.6rem 0.9rem;
      resize: vertical;
      outline: none;
    }

    .run-btn {
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      border: none;
      border-radius: 0.5rem;
      color: #fff;
      font-weight: 600;
      font-size: 0.9rem;
      padding: 0 1.25rem;
      cursor: pointer;
      transition: opacity 0.2s;
    }

    .run-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .hint {
      color: #475569;
      font-size: 0.78rem;
      margin: 0;
    }

    kbd {
      background: #1e2130;
      padding: 1px 5px;
      border-radius: 3px;
    }
  `],
})
export class FileManagerComponent implements OnInit {
  protected readonly agent = inject(FileAgentService)

  protected prompt = signal('')

  private readonly outputEl = viewChild<ElementRef<HTMLPreElement>>('outputEl')

  // Auto-scroll whenever lines change
  constructor() {
    afterEvery(() => {
      // reading this signal registers the dependency
      void this.agent.lines()
      const el = this.outputEl()?.nativeElement
      if (el) el.scrollTop = el.scrollHeight
    })
  }

  async ngOnInit(): Promise<void> {
    await this.agent.initialize()
  }

  async run(): Promise<void> {
    const p = this.prompt().trim()
    if (!p || !this.agent.isReady()) return
    this.prompt.set('')
    await this.agent.invoke(p)
  }

  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault()
      void this.run()
    }
  }
}

<!-- FileManagerComponent template — Angular 21 control-flow syntax -->

<div style="text-align:center">
  <h1>OPFS File Agent</h1>
  <p class="subtitle">Powered by Strands Agents + opfs-worker (Angular&nbsp;21)</p>
</div>

<!-- Status badge -->
<span class="status-badge" [class]="'status-' + agent.status()">
  {{ agent.status() }}
</span>

<!-- Error banner -->
@if (agent.error()) {
  <div class="error-banner">{{ agent.error() }}</div>
}

<!-- Output card -->
<div class="output-card">
  <div class="output-header">
    <span>Agent Output</span>
    <button class="clear-btn" (click)="agent.clearLines()">Clear</button>
  </div>
  <pre #outputEl class="output">
@if (agent.lines().length) {
  @for (line of agent.lines(); track $index) {
{{ line }}
  }
} @else if (agent.status() === 'initialising') {
Initialising agent…
} @else {
Agent ready. Type a command below.
}
  </pre>
</div>

<!-- Input row -->
<div class="input-row">
  <textarea
    rows="2"
    [disabled]="!agent.isReady()"
    [ngModel]="prompt()"
    (ngModelChange)="prompt.set($event)"
    (keydown)="onKeydown($event)"
    placeholder='e.g. "Write a file at /hello.txt with content Hello!"'
  ></textarea>

  <button
    class="run-btn"
    [disabled]="!agent.isReady() || !prompt().trim()"
    (click)="run()"
  >
    Run
  </button>
</div>

<p class="hint">
  Press <kbd>Enter</kbd> to run &nbsp;·&nbsp; <kbd>Shift+Enter</kbd> for newline
</p>
